export default [
	{
		createTime: "2019-05-13 16:07:08",
		iconClass: null,
		id: 20001,
		isEnabled: 1,
		isShow: 1,
		parentId: 0,
		permissionCode: "userManager",
		permissionName: "会员中心",
		permissionType: 0,
		permissionUrl: null,
		sortOrder: 1
	},
	{
		createTime: "2019-05-13 16:07:08",
		iconClass: null,
		id: 20001,
		isEnabled: 1,
		isShow: 1,
		parentId: 20001,
		permissionCode: "userManager",
		permissionName: "会员佣金查询",
		permissionType: 0,
		permissionUrl: "/memberCentreManagement/memberCommissionQuiry",
		sortOrder: 1
	},
	{
		createTime: "2019-05-13 16:07:08",
		iconClass: null,
		id: 20001,
		isEnabled: 1,
		isShow: 1,
		parentId: 20001,
		permissionCode: "userManager",
		permissionName: "注单查询",
		permissionType: 0,
		permissionUrl: "/memberCentreManagement/bettingQuiry",
		sortOrder: 1
	},
	{
		createTime: "2019-05-13 16:07:08",
		iconClass: null,
		id: 20001,
		isEnabled: 1,
		isShow: 1,
		parentId: 20001,
		permissionCode: "userManager",
		permissionName: "所有上级查询",
		permissionType: 0,
		permissionUrl: "/memberCentreManagement/superiorQuiry",
		sortOrder: 1
	},
	{
		createTime: "2019-05-13 16:07:08",
		iconClass: null,
		id: 20001,
		isEnabled: 1,
		isShow: 1,
		parentId: 20001,
		permissionCode: "userManager",
		permissionName: "充值提现记录",
		permissionType: 0,
		permissionUrl: "/memberCentreManagement/rechargeWithdrawalRecord",
		sortOrder: 1
	},
	{
		createTime: "2019-05-13 16:07:08",
		iconClass: null,
		id: 20003,
		isEnabled: 1,
		isShow: 1,
		parentId: 20001,
		permissionCode: "userManager",
		permissionName: "人工入款查询",
		permissionType: 0,
		permissionUrl: "/memberCentreManagement/manualDepositInquiry",
		sortOrder: 1
	},
	{
		createTime: "2019-05-13 16:07:08",
		iconClass: null,
		id: 20002,
		isEnabled: 1,
		isShow: 1,
		parentId: 0,
		permissionCode: "userManager",
		permissionName: "第三方报表",
		permissionType: 0,
		permissionUrl: null,
		sortOrder: 1
	},
	{
		createTime: "2019-05-13 16:07:08",
		iconClass: null,
		id: 20001,
		isEnabled: 1,
		isShow: 1,
		parentId: 20002,
		permissionCode: "userManager",
		permissionName: "第三方盈亏查询",
		permissionType: 0,
		permissionUrl: "/thirdReportManagement/thirdPartyProfitLossInQuiry",
		sortOrder: 1
	},
	{
		createTime: "2019-05-13 16:07:08",
		iconClass: null,
		id: 20001,
		isEnabled: 1,
		isShow: 1,
		parentId: 20002,
		permissionCode: "userManager",
		permissionName: "第三方注单记录",
		permissionType: 0,
		permissionUrl: "/thirdReportManagement/thirdPartyProfitLossInRecord",
		sortOrder: 1
	}
]